// ============================================================
// Location Data — All 60 town/county location pages + 8 NJ county pages
// Each location has unique SEO-optimized content
// ============================================================

export interface LocationData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  region: string;
  fullService: boolean; // NJ = full, out-of-state = limited
  description: string;
  industries: string[];
  caseStudy: {
    title: string;
    challenge: string;
    solution: string;
    results: string[];
  };
  nearbyAreas: string[];
  responseTime: string;
  serviceRadius: string;
}

export interface CountyData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  description: string;
  towns: string[];
  industries: string[];
  caseStudy: {
    title: string;
    challenge: string;
    solution: string;
    results: string[];
  };
}

// Helper to generate a slug from a location name
function toSlug(name: string, stateAbbr: string): string {
  return `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "")}-${stateAbbr.toLowerCase()}`;
}

// ============================================================
// NJ SOUTH JERSEY LOCATIONS
// ============================================================
const southJerseyLocations: LocationData[] = [
  {
    slug: "cherry-hill-nj",
    name: "Cherry Hill",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Serving Cherry Hill's thriving business corridor with enterprise technology solutions for retail, healthcare, and corporate environments.",
    industries: ["Retail", "Healthcare", "Corporate Offices", "Financial Services"],
    caseStudy: {
      title: "Cherry Hill Medical Center",
      challenge: "Outdated communication system affecting patient care coordination",
      solution: "Deployed comprehensive hosted PBX system with Microsoft Teams integration",
      results: ["45% improvement in response times", "Enhanced HIPAA compliance", "Streamlined nurse station communications"],
    },
    nearbyAreas: ["Voorhees", "Marlton", "Mount Laurel", "Haddonfield", "Collingswood"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "camden-nj",
    name: "Camden",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Providing advanced security and technology solutions for Camden's urban businesses, educational institutions, and waterfront developments.",
    industries: ["Education", "Healthcare", "Urban Development", "Government"],
    caseStudy: {
      title: "Camden Waterfront Office Complex",
      challenge: "Multi-tenant building needed unified security and access control",
      solution: "Installed integrated CCTV, access control, and intercom system across 12 floors",
      results: ["Centralized security monitoring", "Reduced unauthorized access by 90%", "Tenant satisfaction increased significantly"],
    },
    nearbyAreas: ["Cherry Hill", "Pennsauken", "Gloucester City", "Collingswood", "Haddon Township"],
    responseTime: "Same-day emergency response within 90 minutes",
    serviceRadius: "20 mile radius",
  },
  {
    slug: "pennsauken-nj",
    name: "Pennsauken",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Delivering reliable security camera and VoIP solutions for Pennsauken's industrial parks, retail centers, and residential communities.",
    industries: ["Industrial", "Retail", "Warehousing", "Residential"],
    caseStudy: {
      title: "Pennsauken Industrial Park",
      challenge: "Large warehouse complex needed comprehensive perimeter security",
      solution: "Deployed 32-camera 4K system with license plate recognition and AI analytics",
      results: ["Eliminated blind spots across 200,000 sq ft", "Reduced theft incidents by 75%", "Remote monitoring from any device"],
    },
    nearbyAreas: ["Camden", "Cherry Hill", "Merchantville", "Maple Shade", "Cinnaminson"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "20 mile radius",
  },
  {
    slug: "voorhees-nj",
    name: "Voorhees",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Trusted technology partner for Voorhees businesses including the Virtua Health campus, retail establishments, and professional offices.",
    industries: ["Healthcare", "Retail", "Professional Services", "Education"],
    caseStudy: {
      title: "Voorhees Professional Office Park",
      challenge: "Medical offices needed HIPAA-compliant security and communications",
      solution: "Integrated access control, encrypted VoIP, and surveillance across 8 suites",
      results: ["Full HIPAA compliance achieved", "Unified communications platform", "30% reduction in IT overhead"],
    },
    nearbyAreas: ["Cherry Hill", "Marlton", "Gibbsboro", "Lindenwold", "Somerdale"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "mount-laurel-nj",
    name: "Mount Laurel",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Supporting Mount Laurel's corporate campuses and business parks with enterprise-grade security and communication systems.",
    industries: ["Corporate", "Technology", "Financial Services", "Healthcare"],
    caseStudy: {
      title: "Mount Laurel Corporate Campus",
      challenge: "Multi-building campus needed unified security infrastructure",
      solution: "Deployed campus-wide IP camera system with centralized NVR and access control",
      results: ["Single-pane security management", "Reduced security staff costs by 25%", "Real-time incident alerting"],
    },
    nearbyAreas: ["Moorestown", "Marlton", "Cherry Hill", "Lumberton", "Hainesport"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "marlton-nj",
    name: "Marlton",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Providing security and technology solutions for Marlton's growing commercial district, medical offices, and residential developments.",
    industries: ["Retail", "Medical", "Residential", "Restaurant"],
    caseStudy: {
      title: "Marlton Shopping Center",
      challenge: "Retail center needed updated surveillance and emergency communication",
      solution: "Installed 24-camera AI-powered system with digital signage integration",
      results: ["Enhanced shopper safety", "Real-time incident detection", "Integrated emergency notifications"],
    },
    nearbyAreas: ["Cherry Hill", "Voorhees", "Mount Laurel", "Medford", "Evesham"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "moorestown-nj",
    name: "Moorestown",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Serving Moorestown's historic downtown businesses and modern office parks with tailored security and communication technology.",
    industries: ["Professional Services", "Retail", "Education", "Residential"],
    caseStudy: {
      title: "Moorestown Main Street Business District",
      challenge: "Historic downtown businesses needed modern security without disrupting aesthetics",
      solution: "Discreet camera installation with wireless connectivity and cloud storage",
      results: ["Preserved historic building character", "24/7 cloud-based monitoring", "Merchant association unified dashboard"],
    },
    nearbyAreas: ["Mount Laurel", "Cherry Hill", "Cinnaminson", "Riverton", "Delran"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "deptford-nj",
    name: "Deptford",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Protecting Deptford's retail corridors and commercial properties with advanced surveillance and alarm systems.",
    industries: ["Retail", "Automotive", "Restaurant", "Industrial"],
    caseStudy: {
      title: "Deptford Mall Area Retailer",
      challenge: "High-traffic retail location experiencing inventory shrinkage",
      solution: "AI-powered video analytics with POS integration and real-time alerts",
      results: ["Shrinkage reduced by 60%", "Staff accountability improved", "ROI achieved within 6 months"],
    },
    nearbyAreas: ["Glassboro", "Woodbury", "West Deptford", "Westville", "National Park"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "glassboro-nj",
    name: "Glassboro",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Supporting Glassboro's university community and growing commercial district with modern security and technology infrastructure.",
    industries: ["Education", "Retail", "Student Housing", "Restaurant"],
    caseStudy: {
      title: "Glassboro Student Housing Complex",
      challenge: "Multi-unit student housing needed comprehensive access control and surveillance",
      solution: "Mobile credential access control with 4K cameras and intercom system",
      results: ["Keyless entry for 200+ residents", "Reduced unauthorized access incidents", "Parent peace-of-mind portal"],
    },
    nearbyAreas: ["Deptford", "Pitman", "Mullica Hill", "Williamstown", "Clayton"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "medford-nj",
    name: "Medford",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Providing security solutions for Medford's charming village businesses, equestrian facilities, and rural commercial properties.",
    industries: ["Retail", "Equestrian", "Agriculture", "Professional Services"],
    caseStudy: {
      title: "Medford Village Business",
      challenge: "Rural commercial property needed reliable security with limited internet",
      solution: "Cellular-connected camera system with solar backup and cloud recording",
      results: ["Reliable monitoring despite rural connectivity", "Zero downtime in 12 months", "Remote access from anywhere"],
    },
    nearbyAreas: ["Marlton", "Mount Laurel", "Shamong", "Tabernacle", "Vincentown"],
    responseTime: "Same-day emergency response within 2.5 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "lakewood-nj",
    name: "Lakewood",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Delivering security and communication solutions for Lakewood's diverse business community, religious institutions, and educational facilities.",
    industries: ["Education", "Religious Institutions", "Retail", "Healthcare"],
    caseStudy: {
      title: "Lakewood Community Center",
      challenge: "Large community facility needed integrated security and communication system",
      solution: "Comprehensive security package with cameras, access control, and PA system",
      results: ["Unified security management", "Emergency notification capability", "Visitor management system"],
    },
    nearbyAreas: ["Toms River", "Brick", "Jackson", "Howell", "Manchester"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
];

// ============================================================
// NJ CENTRAL JERSEY LOCATIONS
// ============================================================
const centralJerseyLocations: LocationData[] = [
  {
    slug: "edison-nj",
    name: "Edison",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Enterprise technology solutions for Edison's diverse business community, from Route 1 corporate offices to local retail establishments.",
    industries: ["Technology", "Pharmaceutical", "Retail", "Corporate"],
    caseStudy: {
      title: "Edison Technology Park",
      challenge: "Tech company needed scalable security for rapid office expansion",
      solution: "Cloud-managed cameras and access control with easy tenant provisioning",
      results: ["Scaled from 2 to 8 suites seamlessly", "Centralized management dashboard", "Per-tenant billing capability"],
    },
    nearbyAreas: ["Woodbridge", "Piscataway", "New Brunswick", "Metuchen", "South Plainfield"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "woodbridge-nj",
    name: "Woodbridge",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Comprehensive security and VoIP solutions for Woodbridge Township's commercial centers, industrial zones, and municipal facilities.",
    industries: ["Industrial", "Retail", "Municipal", "Warehousing"],
    caseStudy: {
      title: "Woodbridge Distribution Center",
      challenge: "Large distribution facility needed loading dock security and inventory tracking",
      solution: "License plate recognition, dock cameras, and integrated alarm system",
      results: ["Eliminated unauthorized dock access", "Shipment verification automated", "Insurance premiums reduced 20%"],
    },
    nearbyAreas: ["Edison", "Perth Amboy", "Carteret", "Rahway", "Avenel"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "new-brunswick-nj",
    name: "New Brunswick",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Technology solutions for New Brunswick's thriving healthcare corridor, university campus, and revitalized downtown business district.",
    industries: ["Healthcare", "Education", "Pharmaceutical", "Restaurant"],
    caseStudy: {
      title: "New Brunswick Medical Office Building",
      challenge: "Multi-specialty medical building needed HIPAA-compliant security",
      solution: "Encrypted camera system with role-based access control and audit logging",
      results: ["Full HIPAA compliance", "Automated visitor logging", "Reduced compliance audit time by 50%"],
    },
    nearbyAreas: ["Edison", "Piscataway", "Highland Park", "East Brunswick", "Somerset"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "piscataway-nj",
    name: "Piscataway",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Supporting Piscataway's research corridor and business parks with cutting-edge security and communication technology.",
    industries: ["Research", "Technology", "Education", "Corporate"],
    caseStudy: {
      title: "Piscataway Research Facility",
      challenge: "Sensitive research lab needed multi-layer security with biometric access",
      solution: "Biometric readers, mantrap entries, and 24/7 video surveillance with AI analytics",
      results: ["Zero unauthorized access events", "Compliance with federal research standards", "Streamlined visitor credentialing"],
    },
    nearbyAreas: ["Edison", "New Brunswick", "South Plainfield", "Dunellen", "Middlesex"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "east-brunswick-nj",
    name: "East Brunswick",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Reliable security and phone system solutions for East Brunswick's Route 18 business corridor and residential communities.",
    industries: ["Retail", "Healthcare", "Education", "Professional Services"],
    caseStudy: {
      title: "East Brunswick Medical Plaza",
      challenge: "Growing medical practice needed scalable phone and security system",
      solution: "Cloud PBX with auto-attendant and integrated waiting room cameras",
      results: ["Call handling capacity doubled", "Patient wait time visibility", "Multi-location phone management"],
    },
    nearbyAreas: ["New Brunswick", "Old Bridge", "South Brunswick", "Spotswood", "Milltown"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "sayreville-nj",
    name: "Sayreville",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Protecting Sayreville's waterfront businesses, industrial properties, and commercial establishments with professional security solutions.",
    industries: ["Industrial", "Waterfront", "Retail", "Manufacturing"],
    caseStudy: {
      title: "Sayreville Waterfront Business",
      challenge: "Waterfront property needed weather-resistant security with marine environment protection",
      solution: "Marine-grade cameras with corrosion-resistant housings and redundant connectivity",
      results: ["Reliable operation in harsh conditions", "Full perimeter coverage", "Remote monitoring capability"],
    },
    nearbyAreas: ["Old Bridge", "South Amboy", "Parlin", "South River", "East Brunswick"],
    responseTime: "Same-day emergency response within 2.5 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "old-bridge-nj",
    name: "Old Bridge",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Serving Old Bridge's growing commercial district with professional security camera installation and business phone systems.",
    industries: ["Retail", "Restaurant", "Professional Services", "Residential"],
    caseStudy: {
      title: "Old Bridge Shopping Plaza",
      challenge: "Strip mall needed unified security across 15 tenant spaces",
      solution: "Shared camera infrastructure with tenant-specific access and recording",
      results: ["Cost-effective shared security", "Individual tenant dashboards", "Parking lot coverage improved"],
    },
    nearbyAreas: ["East Brunswick", "Sayreville", "Marlboro", "Manalapan", "Matawan"],
    responseTime: "Same-day emergency response within 2.5 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "freehold-nj",
    name: "Freehold",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Professional security and technology services for Freehold's historic downtown, courthouse district, and surrounding business community.",
    industries: ["Legal", "Government", "Retail", "Restaurant"],
    caseStudy: {
      title: "Freehold Law Office Complex",
      challenge: "Law firm needed secure document storage area monitoring and client confidentiality",
      solution: "Restricted access zones with biometric entry and encrypted video storage",
      results: ["Client confidentiality enhanced", "Document room access fully audited", "Insurance compliance achieved"],
    },
    nearbyAreas: ["Marlboro", "Manalapan", "Howell", "Colts Neck", "Englishtown"],
    responseTime: "Same-day emergency response within 2.5 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "marlboro-nj",
    name: "Marlboro",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Premium security solutions for Marlboro's upscale residential communities and professional office parks.",
    industries: ["Professional Services", "Healthcare", "Residential", "Education"],
    caseStudy: {
      title: "Marlboro Professional Center",
      challenge: "Medical and dental offices needed after-hours security and patient communication",
      solution: "After-hours alarm system with VoIP integration for emergency call routing",
      results: ["After-hours emergency calls routed properly", "Break-in attempts deterred", "Patient communication improved"],
    },
    nearbyAreas: ["Freehold", "Old Bridge", "Manalapan", "Holmdel", "Matawan"],
    responseTime: "Same-day emergency response within 2.5 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "princeton-nj",
    name: "Princeton",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Central Jersey",
    fullService: true,
    description: "Sophisticated technology solutions for Princeton's research institutions, corporate headquarters, and prestigious commercial properties.",
    industries: ["Research", "Education", "Corporate", "Biotech"],
    caseStudy: {
      title: "Princeton Corporate Headquarters",
      challenge: "Fortune 500 regional office needed enterprise security upgrade",
      solution: "Full campus security overhaul with AI analytics, access control, and unified communications",
      results: ["Enterprise-grade security achieved", "Visitor management automated", "Executive floor secured with biometrics"],
    },
    nearbyAreas: ["West Windsor", "Plainsboro", "Lawrence", "Hopewell", "Montgomery"],
    responseTime: "Same-day emergency response within 3 hours",
    serviceRadius: "30 mile radius",
  },
];

// ============================================================
// NJ JERSEY SHORE LOCATIONS
// ============================================================
const jerseyShoreLocations: LocationData[] = [
  {
    slug: "atlantic-city-nj",
    name: "Atlantic City",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Comprehensive security and technology solutions for Atlantic City's hospitality, gaming, and tourism industries.",
    industries: ["Hospitality", "Gaming", "Tourism", "Restaurant"],
    caseStudy: {
      title: "Atlantic City Boutique Hotel",
      challenge: "Boutique hotel needed modern guest communication and security system",
      solution: "Integrated PBX, digital signage, and 4K surveillance across all floors",
      results: ["Enhanced guest experience", "Reduced front desk call volume 40%", "24/7 property monitoring"],
    },
    nearbyAreas: ["Brigantine", "Ventnor", "Margate", "Pleasantville", "Egg Harbor Township"],
    responseTime: "Same-day emergency response within 45 minutes",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "brigantine-nj",
    name: "Brigantine",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Protecting Brigantine's coastal properties, vacation rentals, and local businesses with weather-resistant security solutions.",
    industries: ["Vacation Rental", "Residential", "Restaurant", "Retail"],
    caseStudy: {
      title: "Brigantine Vacation Rental Property",
      challenge: "Property owner needed remote monitoring for seasonal rental units",
      solution: "Smart lock integration with cameras and noise monitoring for vacation rentals",
      results: ["Remote guest check-in automated", "Property damage prevention", "Noise complaint reduction"],
    },
    nearbyAreas: ["Atlantic City", "Ventnor", "Longport", "Margate", "Pleasantville"],
    responseTime: "Same-day emergency response within 1 hour",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "ocean-city-nj",
    name: "Ocean City",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Security and technology solutions for Ocean City's boardwalk businesses, vacation properties, and year-round commercial establishments.",
    industries: ["Tourism", "Retail", "Vacation Rental", "Restaurant"],
    caseStudy: {
      title: "Ocean City Boardwalk Business",
      challenge: "Seasonal business needed flexible security that scales with tourist season",
      solution: "Cloud-based camera system with seasonal activation and remote monitoring",
      results: ["Off-season cost savings of 60%", "Peak season full coverage", "Remote owner monitoring"],
    },
    nearbyAreas: ["Somers Point", "Marmora", "Sea Isle City", "Strathmere", "Upper Township"],
    responseTime: "Same-day emergency response within 1 hour",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "wildwood-nj",
    name: "Wildwood",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Protecting Wildwood's iconic boardwalk businesses, motels, and entertainment venues with robust security technology.",
    industries: ["Tourism", "Hospitality", "Entertainment", "Retail"],
    caseStudy: {
      title: "Wildwood Motel Complex",
      challenge: "Motel chain needed standardized security across 3 properties",
      solution: "Unified camera and access control platform with centralized management",
      results: ["Consistent security across all properties", "Centralized incident review", "Guest safety improved"],
    },
    nearbyAreas: ["North Wildwood", "Wildwood Crest", "Cape May", "Rio Grande", "Villas"],
    responseTime: "Same-day emergency response within 1.5 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "cape-may-nj",
    name: "Cape May",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Discreet security solutions for Cape May's historic bed & breakfasts, boutique hotels, and Victorian-era commercial properties.",
    industries: ["Hospitality", "Tourism", "Retail", "Historic Properties"],
    caseStudy: {
      title: "Cape May Historic B&B",
      challenge: "Victorian B&B needed modern security without altering historic character",
      solution: "Miniature cameras with wireless connectivity and period-appropriate housings",
      results: ["Historic preservation maintained", "Full property coverage", "Guest privacy respected"],
    },
    nearbyAreas: ["Wildwood", "West Cape May", "Cape May Point", "Lower Township", "Villas"],
    responseTime: "Same-day emergency response within 1.5 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "long-branch-nj",
    name: "Long Branch",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Modern security and communication systems for Long Branch's Pier Village, oceanfront condos, and commercial developments.",
    industries: ["Residential", "Retail", "Restaurant", "Hospitality"],
    caseStudy: {
      title: "Long Branch Oceanfront Condo",
      challenge: "Luxury condo building needed comprehensive security and intercom upgrade",
      solution: "Video intercom, lobby cameras, parking garage access control, and elevator restrictions",
      results: ["Resident satisfaction increased", "Package theft eliminated", "Parking security enhanced"],
    },
    nearbyAreas: ["Asbury Park", "Deal", "West Long Branch", "Eatontown", "Oceanport"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "asbury-park-nj",
    name: "Asbury Park",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Technology solutions for Asbury Park's revitalized boardwalk, music venues, restaurants, and boutique retail establishments.",
    industries: ["Entertainment", "Restaurant", "Retail", "Hospitality"],
    caseStudy: {
      title: "Asbury Park Restaurant & Bar",
      challenge: "Popular venue needed security cameras and a modern phone system for reservations",
      solution: "4K cameras covering dining areas and entrances, plus cloud PBX with reservation routing",
      results: ["Staff and patron safety improved", "Reservation handling streamlined", "Incident documentation for liability"],
    },
    nearbyAreas: ["Long Branch", "Ocean Grove", "Neptune", "Bradley Beach", "Deal"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "point-pleasant-nj",
    name: "Point Pleasant",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Security and VoIP solutions for Point Pleasant's boardwalk attractions, marinas, and year-round business community.",
    industries: ["Tourism", "Marine", "Retail", "Restaurant"],
    caseStudy: {
      title: "Point Pleasant Marina",
      challenge: "Marina needed waterfront surveillance and communication system",
      solution: "Marine-rated cameras with night vision and VoIP system for dock management",
      results: ["24/7 dock monitoring", "Boat theft prevention", "Improved dock communication"],
    },
    nearbyAreas: ["Brick", "Manasquan", "Bay Head", "Brielle", "Wall Township"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "toms-river-nj",
    name: "Toms River",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Comprehensive security and technology services for Toms River's commercial centers, medical facilities, and government buildings.",
    industries: ["Healthcare", "Government", "Retail", "Education"],
    caseStudy: {
      title: "Toms River Medical Center",
      challenge: "Multi-practice medical building needed unified security and phone system",
      solution: "Centralized VoIP with practice-specific routing and HIPAA-compliant cameras",
      results: ["All practices on one phone platform", "Patient privacy maintained", "Emergency protocols automated"],
    },
    nearbyAreas: ["Lakewood", "Brick", "Berkeley Township", "Beachwood", "Island Heights"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "seaside-heights-nj",
    name: "Seaside Heights",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Seasonal and year-round security solutions for Seaside Heights' boardwalk businesses, amusement parks, and commercial properties.",
    industries: ["Tourism", "Entertainment", "Retail", "Restaurant"],
    caseStudy: {
      title: "Seaside Heights Boardwalk Arcade",
      challenge: "Seasonal business needed flexible security with off-season protection",
      solution: "Cellular-connected cameras with motion detection and seasonal monitoring plans",
      results: ["Year-round property protection", "Seasonal cost flexibility", "Remote owner access"],
    },
    nearbyAreas: ["Seaside Park", "Toms River", "Lavallette", "Ortley Beach", "Berkeley Township"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "long-beach-island-nj",
    name: "Long Beach Island",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Protecting Long Beach Island's vacation homes, rental properties, and seasonal businesses with smart security technology.",
    industries: ["Vacation Rental", "Residential", "Retail", "Restaurant"],
    caseStudy: {
      title: "LBI Vacation Rental Portfolio",
      challenge: "Property manager needed remote monitoring for 12 rental properties",
      solution: "Smart locks, exterior cameras, and noise monitoring across all properties",
      results: ["Remote management of all properties", "Guest turnover streamlined", "Property damage reduced"],
    },
    nearbyAreas: ["Barnegat Light", "Beach Haven", "Ship Bottom", "Surf City", "Manahawkin"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "avalon-nj",
    name: "Avalon",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Premium security solutions for Avalon's luxury vacation properties, upscale restaurants, and exclusive commercial establishments.",
    industries: ["Luxury Residential", "Restaurant", "Retail", "Vacation Rental"],
    caseStudy: {
      title: "Avalon Luxury Beach Home",
      challenge: "High-value vacation home needed comprehensive smart security",
      solution: "Integrated alarm, cameras, smart locks, and environmental monitoring",
      results: ["Complete property protection", "Remote homeowner control", "Insurance premium reduction"],
    },
    nearbyAreas: ["Stone Harbor", "Sea Isle City", "Ocean City", "Cape May Court House", "Wildwood"],
    responseTime: "Same-day emergency response within 1.5 hours",
    serviceRadius: "30 mile radius",
  },
];

// ============================================================
// NJ COUNTY LOCATIONS (in /locations/ path)
// ============================================================
const njCountyLocations: LocationData[] = [
  {
    slug: "atlantic-county-nj",
    name: "Atlantic County",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Comprehensive technology services for Atlantic County businesses, from Atlantic City's hospitality industry to suburban commercial establishments.",
    industries: ["Hospitality", "Gaming", "Tourism", "Healthcare", "Retail"],
    caseStudy: {
      title: "Atlantic City Resort Hotel",
      challenge: "Guest communication system modernization across 500 rooms",
      solution: "Integrated PBX system with digital signage and security cameras",
      results: ["Enhanced guest satisfaction scores", "Improved operational efficiency", "Reduced maintenance costs by 35%"],
    },
    nearbyAreas: ["Atlantic City", "Egg Harbor Township", "Galloway", "Hammonton", "Pleasantville", "Ventnor"],
    responseTime: "24/7 hospitality emergency response within 45 minutes",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "burlington-county-nj",
    name: "Burlington County",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Serving Burlington County's military installations, corporate parks, and growing suburban communities with enterprise technology.",
    industries: ["Military", "Corporate", "Healthcare", "Education"],
    caseStudy: {
      title: "Burlington County Office Park",
      challenge: "Multi-tenant office park needed standardized security infrastructure",
      solution: "Campus-wide camera system with tenant-specific access control zones",
      results: ["Unified security management", "Tenant satisfaction improved", "Operating costs reduced"],
    },
    nearbyAreas: ["Mount Laurel", "Moorestown", "Burlington City", "Medford", "Bordentown"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "gloucester-county-nj",
    name: "Gloucester County",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "South Jersey",
    fullService: true,
    description: "Professional security and technology solutions for Gloucester County's growing commercial corridors and industrial facilities.",
    industries: ["Industrial", "Retail", "Education", "Healthcare"],
    caseStudy: {
      title: "Gloucester County Industrial Facility",
      challenge: "Manufacturing plant needed perimeter security and employee access management",
      solution: "Thermal cameras, perimeter detection, and biometric time-clock integration",
      results: ["Perimeter breaches eliminated", "Employee tracking automated", "OSHA compliance improved"],
    },
    nearbyAreas: ["Deptford", "Glassboro", "Washington Township", "Woodbury", "Mullica Hill"],
    responseTime: "Same-day emergency response within 2 hours",
    serviceRadius: "25 mile radius",
  },
  {
    slug: "cape-may-county-nj",
    name: "Cape May County",
    state: "New Jersey",
    stateAbbr: "NJ",
    region: "Jersey Shore",
    fullService: true,
    description: "Year-round and seasonal security solutions for Cape May County's tourism-driven economy, historic properties, and coastal businesses.",
    industries: ["Tourism", "Hospitality", "Vacation Rental", "Restaurant"],
    caseStudy: {
      title: "Cape May County Resort",
      challenge: "Beachfront resort needed comprehensive security for peak season",
      solution: "Scalable camera system with seasonal monitoring and beach access control",
      results: ["Guest safety enhanced", "Seasonal cost management", "Property protection year-round"],
    },
    nearbyAreas: ["Cape May", "Wildwood", "Avalon", "Stone Harbor", "Sea Isle City"],
    responseTime: "Same-day emergency response within 1.5 hours",
    serviceRadius: "30 mile radius",
  },
];

// ============================================================
// PENNSYLVANIA LOCATIONS
// ============================================================
const paLocations: LocationData[] = [
  {
    slug: "philadelphia-pa",
    name: "Philadelphia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "VoIP phone systems, security cameras, and access control solutions for Philadelphia's diverse business landscape, from Center City offices to neighborhood retail.",
    industries: ["Healthcare", "Education", "Legal", "Restaurant"],
    caseStudy: {
      title: "Philadelphia Law Firm",
      challenge: "Multi-office law firm needed unified communications across 3 locations",
      solution: "Cloud PBX with presence management, call recording, and mobile integration",
      results: ["Unified communications across offices", "Client call recording for compliance", "Remote work capability enabled"],
    },
    nearbyAreas: ["King of Prussia", "Norristown", "Conshohocken", "Bensalem", "Camden"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "40 mile radius",
  },
  {
    slug: "king-of-prussia-pa",
    name: "King of Prussia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "Enterprise VoIP and security solutions for King of Prussia's corporate headquarters, retail centers, and technology companies.",
    industries: ["Corporate", "Retail", "Technology", "Pharmaceutical"],
    caseStudy: {
      title: "King of Prussia Corporate Office",
      challenge: "Growing company needed scalable phone system for 200+ employees",
      solution: "Enterprise hosted PBX with Microsoft Teams integration and call center features",
      results: ["Seamless Teams integration", "Call center efficiency improved 35%", "Remote worker support enabled"],
    },
    nearbyAreas: ["Norristown", "Wayne", "Valley Forge", "Conshohocken", "Plymouth Meeting"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "norristown-pa",
    name: "Norristown",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "Professional VoIP and security camera solutions for Norristown's government offices, legal practices, and commercial properties.",
    industries: ["Government", "Legal", "Healthcare", "Retail"],
    caseStudy: {
      title: "Norristown Professional Building",
      challenge: "Mixed-use building needed modern phone system and security upgrade",
      solution: "Multi-tenant VoIP with shared security camera infrastructure",
      results: ["Cost-effective shared infrastructure", "Individual tenant phone systems", "Building-wide security coverage"],
    },
    nearbyAreas: ["King of Prussia", "Conshohocken", "Plymouth Meeting", "Blue Bell", "Bridgeport"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "conshohocken-pa",
    name: "Conshohocken",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "Modern VoIP and security technology for Conshohocken's revitalized business district and corporate office buildings.",
    industries: ["Corporate", "Technology", "Financial Services", "Restaurant"],
    caseStudy: {
      title: "Conshohocken Tech Startup",
      challenge: "Fast-growing startup needed flexible phone system and office security",
      solution: "Cloud PBX with hot-desking and scalable camera system",
      results: ["Phone system scaled with headcount", "Flexible workspace enabled", "Visitor management automated"],
    },
    nearbyAreas: ["Norristown", "King of Prussia", "Plymouth Meeting", "West Conshohocken", "Whitemarsh"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "west-chester-pa",
    name: "West Chester",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "VoIP and security solutions for West Chester's university community, downtown businesses, and surrounding corporate parks.",
    industries: ["Education", "Retail", "Restaurant", "Professional Services"],
    caseStudy: {
      title: "West Chester Restaurant Group",
      challenge: "Multi-location restaurant group needed unified phone and security",
      solution: "Cloud PBX with location-specific routing and camera systems per location",
      results: ["Centralized reservation management", "Loss prevention across locations", "Manager remote monitoring"],
    },
    nearbyAreas: ["Exton", "Downingtown", "Malvern", "Paoli", "Kennett Square"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "bensalem-pa",
    name: "Bensalem",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "Security camera and VoIP solutions for Bensalem's commercial corridors, entertainment venues, and industrial properties.",
    industries: ["Entertainment", "Retail", "Industrial", "Hospitality"],
    caseStudy: {
      title: "Bensalem Entertainment Venue",
      challenge: "Large venue needed comprehensive security and communication system",
      solution: "Multi-zone camera system with event-specific monitoring and staff communication",
      results: ["Event security streamlined", "Staff communication improved", "Incident response time reduced"],
    },
    nearbyAreas: ["Philadelphia", "Levittown", "Langhorne", "Trevose", "Feasterville"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "delaware-county-pa",
    name: "Delaware County",
    state: "Pennsylvania",
    stateAbbr: "PA",
    region: "Pennsylvania",
    fullService: false,
    description: "VoIP phone systems and security solutions for Delaware County's diverse communities from Media to Upper Darby.",
    industries: ["Education", "Healthcare", "Retail", "Government"],
    caseStudy: {
      title: "Delaware County Medical Practice",
      challenge: "Multi-location medical practice needed unified communications",
      solution: "Cloud PBX connecting 4 offices with centralized scheduling and call routing",
      results: ["Patient call handling improved", "Inter-office communication seamless", "After-hours routing automated"],
    },
    nearbyAreas: ["Media", "Upper Darby", "Springfield", "Swarthmore", "Drexel Hill"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
];

// ============================================================
// DELAWARE LOCATIONS
// ============================================================
const deLocations: LocationData[] = [
  {
    slug: "wilmington-de",
    name: "Wilmington",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Enterprise VoIP and security solutions for Wilmington's financial district, corporate headquarters, and downtown businesses.",
    industries: ["Financial Services", "Corporate", "Legal", "Healthcare"],
    caseStudy: {
      title: "Wilmington Financial Services Firm",
      challenge: "Financial firm needed secure communications and compliance-ready recording",
      solution: "Encrypted VoIP with call recording, archiving, and compliance reporting",
      results: ["Regulatory compliance achieved", "Call quality improved significantly", "Archiving automated for audits"],
    },
    nearbyAreas: ["Newark", "New Castle", "Claymont", "Elsmere", "Newport"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "newark-de",
    name: "Newark",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Technology solutions for Newark's university community, Main Street businesses, and surrounding commercial developments.",
    industries: ["Education", "Retail", "Restaurant", "Technology"],
    caseStudy: {
      title: "Newark Main Street Business",
      challenge: "Retail business needed modern phone system and security cameras",
      solution: "Cloud PBX with customer service features and 4K camera system",
      results: ["Customer call handling improved", "Theft prevention enhanced", "Business hours flexibility"],
    },
    nearbyAreas: ["Wilmington", "Elkton", "New Castle", "Bear", "Hockessin"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "middletown-de",
    name: "Middletown",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Growing with Middletown — VoIP and security solutions for Delaware's fastest-growing community and its expanding business district.",
    industries: ["Retail", "Healthcare", "Education", "Professional Services"],
    caseStudy: {
      title: "Middletown Medical Office",
      challenge: "New medical practice needed complete phone and security setup",
      solution: "Turnkey VoIP with patient routing and HIPAA-compliant camera system",
      results: ["Practice operational from day one", "Patient experience optimized", "HIPAA compliance from start"],
    },
    nearbyAreas: ["Odessa", "Townsend", "Smyrna", "New Castle", "Bear"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "new-castle-de",
    name: "New Castle",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "VoIP and security solutions for New Castle's industrial corridor, historic district businesses, and commercial properties.",
    industries: ["Industrial", "Retail", "Government", "Logistics"],
    caseStudy: {
      title: "New Castle Industrial Park",
      challenge: "Logistics company needed warehouse security and communication system",
      solution: "Loading dock cameras, warehouse coverage, and VoIP with warehouse paging",
      results: ["Shipping verification automated", "Warehouse communication improved", "Theft prevention enhanced"],
    },
    nearbyAreas: ["Wilmington", "Newark", "Bear", "Delaware City", "Middletown"],
    responseTime: "Same-day service response within 3 hours",
    serviceRadius: "30 mile radius",
  },
  {
    slug: "dover-de",
    name: "Dover",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Professional VoIP and security technology for Dover's government offices, military-adjacent businesses, and commercial district.",
    industries: ["Government", "Military", "Retail", "Healthcare"],
    caseStudy: {
      title: "Dover Professional Office",
      challenge: "Government contractor needed secure communications and access control",
      solution: "Encrypted VoIP with secure conference rooms and badge-based access control",
      results: ["Security clearance requirements met", "Secure communication established", "Visitor management automated"],
    },
    nearbyAreas: ["Smyrna", "Camden", "Wyoming", "Harrington", "Milford"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "rehoboth-beach-de",
    name: "Rehoboth Beach",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Seasonal and year-round VoIP and security solutions for Rehoboth Beach's tourism businesses, restaurants, and retail shops.",
    industries: ["Tourism", "Restaurant", "Retail", "Vacation Rental"],
    caseStudy: {
      title: "Rehoboth Beach Restaurant",
      challenge: "Popular restaurant needed reservation phone system and security cameras",
      solution: "Cloud PBX with reservation routing and outdoor dining area cameras",
      results: ["Reservation handling improved", "Outdoor area monitored", "Off-season cost savings"],
    },
    nearbyAreas: ["Lewes", "Dewey Beach", "Bethany Beach", "Milton", "Georgetown"],
    responseTime: "Same-day service response within 4 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "lewes-de",
    name: "Lewes",
    state: "Delaware",
    stateAbbr: "DE",
    region: "Delaware",
    fullService: false,
    description: "Technology solutions for Lewes' historic downtown businesses, ferry terminal area, and growing residential communities.",
    industries: ["Tourism", "Retail", "Restaurant", "Marine"],
    caseStudy: {
      title: "Lewes Downtown Business",
      challenge: "Historic district business needed discreet security installation",
      solution: "Miniature cameras with wireless connectivity preserving building aesthetics",
      results: ["Historic character preserved", "Full coverage achieved", "Remote monitoring enabled"],
    },
    nearbyAreas: ["Rehoboth Beach", "Milton", "Cape Henlopen", "Harbeson", "Nassau"],
    responseTime: "Same-day service response within 4 hours",
    serviceRadius: "35 mile radius",
  },
];

// ============================================================
// MARYLAND LOCATIONS
// ============================================================
const mdLocations: LocationData[] = [
  {
    slug: "baltimore-md",
    name: "Baltimore",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "VoIP phone systems and security camera solutions for Baltimore's Inner Harbor businesses, healthcare facilities, and commercial properties.",
    industries: ["Healthcare", "Hospitality", "Education", "Corporate"],
    caseStudy: {
      title: "Baltimore Medical Practice",
      challenge: "Growing medical practice needed multi-location phone system",
      solution: "Cloud PBX connecting 3 Baltimore-area offices with centralized scheduling",
      results: ["Patient routing optimized", "Inter-office transfers seamless", "After-hours coverage automated"],
    },
    nearbyAreas: ["Towson", "Columbia", "Ellicott City", "Catonsville", "Dundalk"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "40 mile radius",
  },
  {
    slug: "towson-md",
    name: "Towson",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "Professional VoIP and security solutions for Towson's university area, business district, and medical offices.",
    industries: ["Education", "Healthcare", "Retail", "Legal"],
    caseStudy: {
      title: "Towson Professional Building",
      challenge: "Mixed-use professional building needed modern communications",
      solution: "Multi-tenant VoIP system with shared lobby security cameras",
      results: ["Tenant communications modernized", "Building security enhanced", "Operating costs shared effectively"],
    },
    nearbyAreas: ["Baltimore", "Lutherville", "Timonium", "Cockeysville", "Hunt Valley"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "columbia-md",
    name: "Columbia",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "Enterprise VoIP and security technology for Columbia's planned community businesses, corporate offices, and commercial centers.",
    industries: ["Corporate", "Technology", "Healthcare", "Retail"],
    caseStudy: {
      title: "Columbia Technology Company",
      challenge: "Tech company needed unified communications for hybrid workforce",
      solution: "Cloud PBX with video conferencing, mobile apps, and hot-desking",
      results: ["Hybrid work fully supported", "Communication costs reduced 30%", "Employee satisfaction improved"],
    },
    nearbyAreas: ["Ellicott City", "Laurel", "Savage", "Jessup", "Elkridge"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "ellicott-city-md",
    name: "Ellicott City",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "VoIP and security solutions for Ellicott City's historic Main Street businesses and surrounding commercial developments.",
    industries: ["Retail", "Restaurant", "Professional Services", "Education"],
    caseStudy: {
      title: "Ellicott City Historic District Business",
      challenge: "Historic district restaurant needed modern phone and security without altering building",
      solution: "Wireless camera system and cloud PBX with minimal physical installation",
      results: ["Historic building preserved", "Modern communication capability", "Security without construction"],
    },
    nearbyAreas: ["Columbia", "Catonsville", "Oella", "Ilchester", "Clarksville"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "annapolis-md",
    name: "Annapolis",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "Professional VoIP and security technology for Annapolis' maritime businesses, government offices, and historic downtown establishments.",
    industries: ["Government", "Marine", "Tourism", "Restaurant"],
    caseStudy: {
      title: "Annapolis Marina Business",
      challenge: "Marina and yacht club needed waterfront security and communication system",
      solution: "Marine-rated cameras with VoIP integration for dock management",
      results: ["Waterfront fully monitored", "Dock communication improved", "Member satisfaction increased"],
    },
    nearbyAreas: ["Severna Park", "Arnold", "Edgewater", "Crofton", "Bowie"],
    responseTime: "Same-day service response within 4 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "bohemia-md",
    name: "Bohemia",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "VoIP and security solutions for Bohemia's rural businesses, agricultural operations, and waterfront properties along the Chesapeake.",
    industries: ["Agriculture", "Marine", "Residential", "Retail"],
    caseStudy: {
      title: "Bohemia Waterfront Property",
      challenge: "Remote waterfront property needed reliable security with limited infrastructure",
      solution: "Cellular-connected cameras with solar power and cloud storage",
      results: ["Reliable monitoring despite rural location", "Zero infrastructure dependency", "Remote access from anywhere"],
    },
    nearbyAreas: ["Elkton", "Chesapeake City", "North East", "Cecilton", "Warwick"],
    responseTime: "Same-day service response within 4 hours",
    serviceRadius: "40 mile radius",
  },
  {
    slug: "elkton-md",
    name: "Elkton",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "Professional VoIP and security solutions for Elkton's commercial corridor, industrial facilities, and growing business community.",
    industries: ["Industrial", "Retail", "Healthcare", "Logistics"],
    caseStudy: {
      title: "Elkton Distribution Center",
      challenge: "Distribution facility at I-95 corridor needed security and communication upgrade",
      solution: "Warehouse cameras, loading dock monitoring, and VoIP with paging system",
      results: ["Shipping verification improved", "Employee communication enhanced", "Theft incidents eliminated"],
    },
    nearbyAreas: ["Newark DE", "North East", "Rising Sun", "Perryville", "Chesapeake City"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
  {
    slug: "bel-air-md",
    name: "Bel Air",
    state: "Maryland",
    stateAbbr: "MD",
    region: "Maryland",
    fullService: false,
    description: "VoIP phone systems and security cameras for Bel Air's thriving downtown, medical offices, and commercial developments.",
    industries: ["Healthcare", "Retail", "Legal", "Education"],
    caseStudy: {
      title: "Bel Air Medical Complex",
      challenge: "Multi-specialty medical building needed unified phone system",
      solution: "Cloud PBX with specialty-specific call routing and patient callback features",
      results: ["Patient call experience improved", "Specialty routing automated", "After-hours coverage seamless"],
    },
    nearbyAreas: ["Aberdeen", "Havre de Grace", "Edgewood", "Fallston", "Forest Hill"],
    responseTime: "Same-day service response within 3.5 hours",
    serviceRadius: "35 mile radius",
  },
];

// ============================================================
// REGIONAL LOCATION
// ============================================================
const regionalLocations: LocationData[] = [
  {
    slug: "delaware-valley",
    name: "Delaware Valley",
    state: "Multi-State",
    stateAbbr: "US",
    region: "Delaware Valley",
    fullService: false,
    description: "Serving the entire Delaware Valley region with VoIP phone systems, security cameras, and technology solutions across New Jersey, Pennsylvania, Delaware, and Maryland.",
    industries: ["Corporate", "Healthcare", "Education", "Retail", "Hospitality"],
    caseStudy: {
      title: "Delaware Valley Multi-Location Business",
      challenge: "Regional business with offices in NJ, PA, and DE needed unified communications",
      solution: "Enterprise cloud PBX connecting all locations with centralized management",
      results: ["All locations on one platform", "Inter-office calling free", "Centralized IT management"],
    },
    nearbyAreas: ["Philadelphia", "Cherry Hill", "Wilmington", "Camden", "King of Prussia"],
    responseTime: "Regional service response within 4 hours",
    serviceRadius: "100 mile radius",
  },
];

// ============================================================
// COUNTY PAGES (8 NJ counties under /counties/ path)
// ============================================================
export const COUNTY_DATA: CountyData[] = [
  {
    slug: "atlantic-county-nj",
    name: "Atlantic County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Full-service security and technology solutions for all 23 municipalities in Atlantic County, from Atlantic City's boardwalk to Hammonton's agricultural businesses.",
    towns: ["Atlantic City", "Brigantine", "Egg Harbor Township", "Galloway", "Hammonton", "Pleasantville", "Ventnor", "Margate", "Longport", "Absecon", "Linwood", "Somers Point", "Northfield"],
    industries: ["Hospitality", "Gaming", "Tourism", "Agriculture", "Healthcare"],
    caseStudy: {
      title: "Atlantic County Hotel Group",
      challenge: "Hotel chain needed standardized security and phone systems across 5 properties",
      solution: "Unified VoIP and camera platform with centralized management dashboard",
      results: ["Consistent guest experience", "Centralized security monitoring", "IT management costs reduced 40%"],
    },
  },
  {
    slug: "burlington-county-nj",
    name: "Burlington County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Security cameras, VoIP, and access control for Burlington County's military-adjacent businesses, corporate parks, and suburban communities.",
    towns: ["Mount Laurel", "Moorestown", "Burlington City", "Bordentown", "Medford", "Evesham", "Cinnaminson", "Delran", "Lumberton", "Pemberton"],
    industries: ["Military", "Corporate", "Healthcare", "Education", "Retail"],
    caseStudy: {
      title: "Burlington County Corporate Campus",
      challenge: "Large corporate campus needed security infrastructure upgrade",
      solution: "Campus-wide IP camera deployment with access control and visitor management",
      results: ["Complete campus coverage", "Visitor tracking automated", "Security response time improved"],
    },
  },
  {
    slug: "camden-county-nj",
    name: "Camden County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Comprehensive security and technology solutions for Camden County's diverse communities, from Cherry Hill's retail corridor to Camden's waterfront developments.",
    towns: ["Cherry Hill", "Camden", "Pennsauken", "Voorhees", "Haddonfield", "Collingswood", "Gloucester Township", "Winslow", "Lindenwold", "Stratford"],
    industries: ["Healthcare", "Education", "Retail", "Government", "Technology"],
    caseStudy: {
      title: "Camden County Healthcare System",
      challenge: "Regional healthcare system needed unified security across 4 facilities",
      solution: "Enterprise security platform with HIPAA-compliant cameras and access control",
      results: ["HIPAA compliance across all facilities", "Centralized security operations center", "Patient and staff safety enhanced"],
    },
  },
  {
    slug: "cape-may-county-nj",
    name: "Cape May County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Year-round and seasonal security solutions for Cape May County's tourism economy, from Cape May's Victorian B&Bs to Wildwood's boardwalk businesses.",
    towns: ["Cape May", "Wildwood", "North Wildwood", "Wildwood Crest", "Stone Harbor", "Avalon", "Sea Isle City", "Ocean City", "Upper Township", "Middle Township"],
    industries: ["Tourism", "Hospitality", "Vacation Rental", "Restaurant", "Retail"],
    caseStudy: {
      title: "Cape May County Vacation Rental Group",
      challenge: "Property management company needed security for 25+ rental properties",
      solution: "Standardized smart lock and camera package with centralized management",
      results: ["All properties monitored from one dashboard", "Guest check-in automated", "Property damage reduced significantly"],
    },
  },
  {
    slug: "cumberland-county-nj",
    name: "Cumberland County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Security and technology solutions for Cumberland County's agricultural businesses, manufacturing facilities, and commercial establishments.",
    towns: ["Vineland", "Millville", "Bridgeton", "Commercial Township", "Deerfield", "Fairfield", "Hopewell", "Lawrence", "Maurice River", "Upper Deerfield"],
    industries: ["Agriculture", "Manufacturing", "Healthcare", "Retail", "Food Processing"],
    caseStudy: {
      title: "Cumberland County Food Processing Plant",
      challenge: "Food processing facility needed security and temperature monitoring",
      solution: "Camera system with environmental sensors and compliance reporting",
      results: ["FDA compliance monitoring automated", "Product safety enhanced", "Facility security improved"],
    },
  },
  {
    slug: "gloucester-county-nj",
    name: "Gloucester County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Professional security and technology services for Gloucester County's growing commercial corridors, from Deptford's retail centers to Mullica Hill's business district.",
    towns: ["Deptford", "Glassboro", "Washington Township", "Woodbury", "Mullica Hill", "Pitman", "Mantua", "West Deptford", "Woolwich", "Swedesboro"],
    industries: ["Retail", "Education", "Industrial", "Healthcare", "Agriculture"],
    caseStudy: {
      title: "Gloucester County Retail Center",
      challenge: "Shopping center needed comprehensive security upgrade",
      solution: "AI-powered camera system with parking lot coverage and tenant integration",
      results: ["Shoplifting reduced significantly", "Parking lot safety improved", "Tenant security dashboards provided"],
    },
  },
  {
    slug: "ocean-county-nj",
    name: "Ocean County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Security and VoIP solutions for Ocean County's barrier island businesses, mainland commercial centers, and growing retirement communities.",
    towns: ["Toms River", "Lakewood", "Brick", "Jackson", "Long Beach Island", "Seaside Heights", "Point Pleasant", "Barnegat", "Stafford", "Manchester"],
    industries: ["Healthcare", "Retail", "Tourism", "Education", "Senior Living"],
    caseStudy: {
      title: "Ocean County Senior Living Community",
      challenge: "Senior living facility needed emergency communication and security system",
      solution: "Nurse call integration with VoIP, cameras in common areas, and access control",
      results: ["Resident safety enhanced", "Emergency response time improved", "Family communication portal enabled"],
    },
  },
  {
    slug: "salem-county-nj",
    name: "Salem County",
    state: "New Jersey",
    stateAbbr: "NJ",
    description: "Security and technology solutions for Salem County's agricultural operations, industrial facilities, and small-town businesses.",
    towns: ["Salem", "Pennsville", "Carneys Point", "Woodstown", "Pilesgrove", "Alloway", "Elsinboro", "Lower Alloways Creek", "Mannington", "Quinton"],
    industries: ["Agriculture", "Industrial", "Energy", "Retail", "Government"],
    caseStudy: {
      title: "Salem County Agricultural Operation",
      challenge: "Large farm operation needed perimeter security and equipment monitoring",
      solution: "Solar-powered cameras with cellular connectivity and equipment GPS tracking",
      results: ["Equipment theft eliminated", "Perimeter monitoring 24/7", "Remote farm management enabled"],
    },
  },
];

// ============================================================
// COMBINED EXPORT
// ============================================================
export const ALL_LOCATIONS: LocationData[] = [
  ...southJerseyLocations,
  ...centralJerseyLocations,
  ...jerseyShoreLocations,
  ...njCountyLocations,
  ...paLocations,
  ...deLocations,
  ...mdLocations,
  ...regionalLocations,
];

// Helper to get location by slug
export function getLocationBySlug(slug: string): LocationData | undefined {
  return ALL_LOCATIONS.find((loc) => loc.slug === slug);
}

// Helper to get county by slug
export function getCountyBySlug(slug: string): CountyData | undefined {
  return COUNTY_DATA.find((c) => c.slug === slug);
}

// Services list for location pages
export const LOCATION_SERVICES = [
  { title: "Alarm Systems", description: "24/7 monitored alarm systems with instant alerts", icon: "Bell", href: "/services/intrusion-detection" },
  { title: "CCTV / Video Surveillance", description: "4K AI-powered security cameras with analytics", icon: "Camera", href: "/services/video-surveillance" },
  { title: "Access Control & Card Access", description: "Keyless entry and visitor management", icon: "KeyRound", href: "/services/access-control" },
  { title: "VoIP Phone Systems", description: "Enterprise VoIP with Microsoft Teams integration", icon: "Phone", href: "/services/voip" },
  { title: "Fire Alarm Systems", description: "NFPA 72 compliant with 24/7 monitoring", icon: "Flame", href: "/services/fire-alarm-systems" },
  { title: "Digital Signage", description: "Dynamic displays with LEDConnect platform", icon: "Monitor", href: "/services/ai-voice-agent" },
  { title: "Network & Low-Voltage Cabling", description: "Structured cabling for data and voice", icon: "Cable", href: "/contact" },
  { title: "Intercom Systems", description: "Building-wide communication solutions", icon: "MessageSquare", href: "/contact" },
];
