/**
 * FreshBooks OAuth callback — Vercel serverless function
 * GET /api/auth/freshbooks-callback?code=...
 *
 * This handles the redirect from FreshBooks after Derek authorizes the app.
 * It exchanges the authorization code for access + refresh tokens and
 * stores them in the environment (prints them so Derek can copy to Vercel).
 *
 * Usage (one-time setup or token renewal):
 *   1. Derek visits the auth URL (generated by /api/auth/freshbooks-start)
 *   2. He authorizes in FreshBooks
 *   3. FreshBooks redirects to this endpoint with ?code=...
 *   4. This endpoint exchanges the code for tokens and displays them
 *   5. Derek copies FRESHBOOKS_REFRESH_TOKEN to Vercel env vars
 */

import type { VercelRequest, VercelResponse } from "@vercel/node";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { code, error } = req.query;

  if (error) {
    return res.status(400).send(`<h1>Authorization failed</h1><p>${error}</p>`);
  }

  if (!code || typeof code !== "string") {
    return res.status(400).send("<h1>Missing authorization code</h1>");
  }

  const clientId = process.env.FRESHBOOKS_CLIENT_ID;
  const clientSecret = process.env.FRESHBOOKS_CLIENT_SECRET;
  // Must match exactly what was sent in the authorization request and registered in FreshBooks portal
  const redirectUri = "https://youneedled.com/api/auth/freshbooks-callback";

  if (!clientId || !clientSecret) {
    return res.status(500).send("<h1>FRESHBOOKS_CLIENT_ID and FRESHBOOKS_CLIENT_SECRET not set in Vercel</h1>");
  }

  try {
    const tokenRes = await fetch("https://api.freshbooks.com/auth/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        grant_type: "authorization_code",
        client_id: clientId,
        client_secret: clientSecret,
        code,
        redirect_uri: redirectUri,
      }),
    });

    const tokens = await tokenRes.json();

    if (!tokenRes.ok || tokens.error) {
      return res.status(400).send(
        `<h1>Token exchange failed</h1><pre>${JSON.stringify(tokens, null, 2)}</pre>`
      );
    }

    const refreshToken = tokens.refresh_token;
    const accessToken = tokens.access_token;

    // Auto-persist the refresh token to Vercel env var if configured
    let autoPersisted = false;
    const vercelApiToken = process.env.VERCEL_API_TOKEN;
    const vercelProjectId = process.env.VERCEL_PROJECT_ID;
    const vercelEnvId = process.env.VERCEL_REFRESH_ENV_ID;
    if (vercelApiToken && vercelProjectId && vercelEnvId) {
      const patchRes = await fetch(
        `https://api.vercel.com/v9/projects/${vercelProjectId}/env/${vercelEnvId}`,
        {
          method: "PATCH",
          headers: { Authorization: `Bearer ${vercelApiToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({ value: refreshToken }),
        }
      );
      autoPersisted = patchRes.ok;
    }

    const syncSecret = process.env.SYNC_SECRET || "YOUR_SYNC_SECRET";

    return res.status(200).send(`<!DOCTYPE html>
<html>
<head><title>FreshBooks Connected ✓</title>
<style>body{font-family:sans-serif;max-width:700px;margin:40px auto;padding:20px}
.token{background:#f0f7ff;border:1px solid #0e319a;padding:12px;border-radius:6px;word-break:break-all;font-family:monospace;font-size:13px}
.step{background:#f8f8f8;padding:16px;border-radius:8px;margin:12px 0}
.success{background:#f0fff4;border:1px solid #22863a;padding:16px;border-radius:8px;margin:12px 0}
h1{color:#0e319a}</style></head>
<body>
<h1>✓ FreshBooks Connected Successfully</h1>
${autoPersisted
  ? `<div class="success"><strong>✓ Refresh token automatically saved to Vercel.</strong> No manual steps needed — the daily sync will use this token and auto-rotate it on each run.</div>`
  : `<p>Copy the refresh token below into your Vercel environment variables.</p>
<div class="step">
<h3>Add to Vercel (FRESHBOOKS_REFRESH_TOKEN)</h3>
<div class="token">${refreshToken}</div>
</div>`
}

<div class="step">
<h3>${autoPersisted ? "Test the sync now" : "After adding to Vercel, test the sync"}</h3>
<div class="token">curl -X POST https://youneedled.com/api/sync/manus-freshbooks?dry_run=1 \\<br>  -H "Authorization: Bearer ${syncSecret}"</div>
</div>

<p style="color:#666;font-size:12px;margin-top:32px">Access token (short-lived, expires in 12h): ${accessToken.substring(0, 20)}...</p>
</body></html>`);
  } catch (err) {
    return res.status(500).send(`<h1>Error</h1><pre>${err}</pre>`);
  }
}
